notes/app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("", IndexView, name="home"),
    path("create/", CreateView, name="create"),
    path("edit/<int:pk>", EditView, name="edit"),
    path("delete/<int:pk>", DeleteView, name="delete"),
]

notes/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
    path("auth/", include("user.urls")),
]

notes/user/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("register/", SignUp, name="register"),
    path("login/", SignIn, name="login"),
    path("logout/", SignOut, name="logout"),
]

notes/app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Note(models.Model):
    title = models.CharField(max_length=500, unique=True)
    content = models.CharField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    user_name = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_name"
    )

    def __str__(self):
        return f"{self.title} | {self.user_name}"

notes/app/forms.py
from django.forms import ModelForm
from .models import *


class CreateNoteForm(ModelForm):
    class Meta:
        model = Note
        fields = "__all__"


class EditNoteForm(ModelForm):
    class Meta:
        model = Note
        fields = ("title", "content")

notes/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

notes/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *

# Create your views here.


def IndexView(request):
    if request.user.is_authenticated:
        return render(
            request,
            "app/index.html",
            {"notes": Note.objects.filter(user_name=request.user).order_by('-pk').all()},
        )
    else:
        return render(
            request,
            "app/index.html",
            {"notes": []},
        )


def CreateView(request):
    if request.method == "POST":
        form = CreateNoteForm(request.POST)
        if form.is_valid():
            form.cleaned_data
            form.save()
            return redirect("/")

        form = CreateNoteForm()
        return render(request, "app/create.html", {"form": form})

    form = CreateNoteForm()
    return render(request, "app/create.html", {"form": form})


def EditView(request, pk):
    note = get_object_or_404(Note, pk=pk)
    if request.method == "POST":
        form = EditNoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            return redirect("/")

    form = EditNoteForm(instance=note)
    return render(request, "app/edit.html", {"form": form})


def DeleteView(request, pk):
    note = get_object_or_404(Note, pk=pk)
    note.delete()
    return redirect("/")

notes/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import *

# Create your views here.


def SignUp(request):
    if request.user.is_authenticated:
        return redirect("/auth/login/")
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/auth/login/")
        else:
            form = UserCreationForm()
            return render(
                request,
                "user/register.html",
                {"form": form, "mssg": "Somthing Went Worng !"},
            )
    form = UserCreationForm()
    return render(request, "user/register.html", {"form": form})


def SignIn(request):
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        user_name = request.POST.get("username")
        pass_word = request.POST.get("password")
        user = authenticate(request, username=user_name, password=pass_word)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            form = AuthenticationForm()
            return render(
                request,
                "user/login.html",
                {"form": form, "mssg": "Somthing Went Wrong !"},
            )

    form = AuthenticationForm()
    return render(request, "user/login.html", {"form": form})


def SignOut(request):
    logout(request)
    return redirect("/")

notes/templates/app/create.html
{% extends 'base.html' %} {% block content %}
<div class="card col-lg-5 mx-auto mt-5 col-11" style="min-height: 58vh">
  <div
    class="card-header py-2 d-flex justify-content-between px-2 align-items-center"
  >
    <h4 class="fs-2 d-inline ps-2">Create Notes</h4>
    <a href="/" class="btn btn-danger btn-sm py-2 px-4">Home</a>
  </div>
  <div class="card-body">
    <form class="p-2" method="POST">
      {% csrf_token %}

      <div class="form-group">
        <label class="form-label mb-1">Title</label>
        {{form.title}}
      </div>
      <div class="form-group mt-4">
        <label class="form-label mb-1">Content</label>
        {{form.content}}
      </div>
      <div class="form-group mt-2 d-none">
        <label class="form-label mb-1">Username</label>
        <select name="user_name" required="" id="id_user_name">
          <option value="{{request.user.pk}}">{{request.user}}</option>
        </select>
      </div>
      <button type="submit" class="btn btn-danger mt-4 px-4 py-2">
        Save Note 
      </button>
    </form>
  </div>
</div>

{% endblock content %}

notes/templates/app/edit.html
{% extends 'base.html' %} {% block content %}
<div class="card col-lg-5 mx-auto mt-5 col-11" style="min-height: 58vh">
  <div
    class="card-header py-2 d-flex justify-content-between px-2 align-items-center"
  >
    <h4 class="fs-2 d-inline ps-2">Edit Note</h4>
    <a href="/" class="btn btn-danger btn-sm py-2 px-4">Home</a>
  </div>
  <div class="card-body">
    <form class="p-2" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label class="form-label mb-1">Title</label>
        {{form.title}}
      </div>
      <div class="form-group mt-4">
        <label class="form-label mb-1">Content</label>
        {{form.content}}
      </div>
      <button type="submit" class="btn btn-danger mt-4 px-4 py-2">
        Save Note
      </button>
    </form>
  </div>
</div>

{% endblock content %}

notes/templates/app/index.html
{% extends 'base.html' %} {% block content %}
<div class="card col-lg-6 mx-auto mt-5 col-11">
  <div
    class="card-header py-2 px-4 d-flex justify-content-between px-2 align-items-center"
  >
    <h4 class="fs-2 d-inline ">Quick Notes</h4>
    <div class="dropdown open">
      <a
        class="btn btn-sm btn-danger px-2 py-2 dropdown-toggle"
        type="button"
        id="triggerId"
        data-bs-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
      {% if request.user.is_authenticated %}
        {{request.user}}
        {% else %}
        <span>Create Note</span>
      {% endif %}
        
      </a>
      <div
        class="dropdown-menu dropdown-menu-end text-center shadow-lg"
        aria-labelledby="triggerId"
      >
        {% if request.user.is_authenticated %}
        <a class="dropdown-item" href="/create/">Create Note</a>
        <a class="dropdown-item" href="/auth/logout/">Log Out</a>
        {% else %}
        <a class="dropdown-item" href="/auth/register/">Register</a>
        <a class="dropdown-item" href="/auth/login/">Login</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="card-body" style="height: 55vh; overflow-y: scroll">
    {% for note in notes %}
    <div
      class="mb-3 card-header rounded-2 px-4 py-3 border-0 shadow-sm d-flex justify-content-between align-items-center"
    >
      <hgroup>
        <span class="text-danger text-capitalize" style="font-size: 13px"
          >{{note.user_name}} | {{note.date | date}}</span
        >
        <h5 class="card-text text-dark mt-3 fw-bold">{{note.title}}</h5>
        <p class="card-text mt-3 text-muted">{{note.content}}</p>
      </hgroup>
      <div class="d-flex flex-column gap-1">
        <a href="/edit/{{note.pk}}" class="btn btn-sm btn-outline-dark px-2"
          ><i class="fas fa-pen-alt"></i
        ></a>
        <a href="/delete/{{note.pk}}" class="btn btn-sm btn-outline-danger px-2"
          ><i class="fas fa-trash"></i
        ></a>
      </div>
    </div>
    {% empty %}
    <p>Note Is Not Present</p>
    {% endfor %}
  </div>
</div>
{% endblock content %}

notes/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>QuickNotes</title>
    {% include 'heads.html' %}
  </head>

  <body class="bg-dark">
    <main>
      {% block content %}

      {% endblock %}
    </main>
    
    {% include 'scripts.html' %}
  </body>
</html>

notes/templates/heads.html
<!-- Required meta tags -->
<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>
<!-- Bootstrap CSS v5.2.1 -->
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
  crossorigin="anonymous"
/>
<!-- FontAwesome 6.2.0 CSS -->
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
  integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
/>

<style>
  ::-webkit-scrollbar {
    display: none !important;
  }
  body {
    font-family: "Trebuchet MS", "Lucida Sans Unicode", "Lucida Grande",
      "Lucida Sans", Arial, sans-serif;
  }

  #id_title,
  #id_content,
  #id_email,
  #id_username,
  #id_password1,
  #id_password2,
  #id_password {
    display: block;
    width: 100%;
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: var(--bs-body-color);
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    background-color: var(--bs-body-bg);
    background-clip: padding-box;
    border: var(--bs-border-width) solid var(--bs-border-color);
    border-radius: var(--bs-border-radius);
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }
</style>

notes/templates/scripts.html
<!-- Bootstrap JavaScript Libraries -->
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  crossorigin="anonymous"
></script>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
  integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
  crossorigin="anonymous"
></script>

<!-- (Optional) Use CSS or JS implementation -->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js"
  integrity="sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

notes/templates/user/login.html
{% extends 'base.html' %} {% block content %}
<div class="card col-lg-4 mx-auto mt-5 col-11" style="min-height: 60vh">
  <div
    class="card-header py-2 d-flex justify-content-between px-2 align-items-center"
  >
    <h4 class="fs-2 d-inline ps-2">Login</h4>
    <a href="/" class="btn btn-danger btn-sm py-2 px-4">Home</a>
  </div>
  <div class="card-body">
    {% if mssg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
      {{mssg}}
    </div>

    {% endif %}
    <form class="p-2" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label class="form-label mb-1">Username</label>
        {{form.username}}
      </div>
      <div class="form-group mt-3">
        <label class="form-label mb-1">Password</label>
        {{form.password}}
      </div>
      <div
        class="d-flex justify-content-between flex-column align-items-center gap-3 py-4"
      >
        <button type="submit" class="btn btn-danger px-4 py-2 w-100">
          Login
        </button>
        <span class="text-muted">
          Don't have an account ?
          <a href="/auth/register/">Register</a>
        </span>
      </div>
      {% for err in form.errors %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
        {{err}}
      </div>

      {% endfor %}
    </form>
  </div>
</div>

{% endblock content %}

notes/templates/user/register.html
{% extends 'base.html' %} {% block content %}
<div class="card col-lg-4 mx-auto mt-3 col-11" style="min-height: 60vh">
  <div
    class="card-header py-2 d-flex justify-content-between px-2 align-items-center"
  >
    <h4 class="fs-2 d-inline ps-2">Register</h4>
    <a href="/" class="btn btn-danger btn-sm py-2 px-4">Home</a>
  </div>
  <div class="card-body">
    {% if mssg %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
      {{mssg}}
    </div>

    {% endif %}

    <form class="p-3" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label class="form-label mb-1">Username</label>
        {{form.username}}
      </div>
      <div class="form-group mt-3">
        <label class="form-label mb-1">Email</label>
        {{form.email}}
      </div>
      <div class="form-group mt-3">
        <label class="form-label mb-1">Password</label>
        {{form.password1}}
      </div>
      <div class="form-group mt-3">
        <label class="form-label mb-1">Confirm Password</label>
        {{form.password2}}
      </div>
      <div
        class="d-flex justify-content-between flex-column align-items-center gap-3 py-4"
      >
        <button type="submit" class="btn btn-danger px-4 py-2 w-100">
          Register
        </button>
        <span class="text-muted">
          Already have an account ?
          <a href="/auth/login/"> Login</a>
        </span>
      </div>

      {% for field, errors in form.errors.items %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
        <div>{{ field }}</div>
        {% for error in errors %}
        <p>{{ error }}</p>
        {% endfor %}
      </div>
      {% endfor %}
    </form>
  </div>
</div>

{% endblock content %}